### ISSUE TITLE
a8r.io prefix is not human-friendly

### ISSUE THREAD

**Issue by philoserf** [ambassadorlabs/k8s-for-humans#4]
While it may be short, pithy, even clever, the prefix`a8r.io/` is not friendly to humans. Perhaps the `humans.txt` project might have been `h4s.txt`. `k8s` works. Some of the other cases of letter, digit, letter do too. Most are not human-friendly. `a8r.io` is in that human-unfriendly basket.

**Comment by AverageMarcus** [comment]
It might be worth extending the current recommended labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

E.g. instead of `a8r.io/description` it'd be `app.kubernetes.io/description`
